spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orders
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081